// <auto-generated />
using AkijFood.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AkijFood.Migrations
{
    [DbContext(typeof(AkijFoodContext))]
    [Migration("20210701181751_AkijFood1")]
    partial class AkijFood1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AkijFood.Models.tblColdDrink", b =>
                {
                    b.Property<int>("intColdDrinksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("numQuantity")
                        .HasColumnType("real");

                    b.Property<float>("numUnitPrice")
                        .HasColumnType("real");

                    b.Property<string>("strColdDrinksName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("intColdDrinksId");

                    b.ToTable("tblColdDrink");

                    b.HasData(
                        new
                        {
                            intColdDrinksId = 1,
                            numQuantity = 450f,
                            numUnitPrice = 20f,
                            strColdDrinksName = "Clemon"
                        },
                        new
                        {
                            intColdDrinksId = 2,
                            numQuantity = 500f,
                            numUnitPrice = 25f,
                            strColdDrinksName = "Frutika"
                        },
                        new
                        {
                            intColdDrinksId = 3,
                            numQuantity = 600f,
                            numUnitPrice = 30f,
                            strColdDrinksName = "Speed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
